sudo: required
language: java
install: skip
os: linux
dist: focal
jdk: 
- openjdk17
services:
- docker

before_install:

script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
- export JAVA_HOME=$HOME/openjdk17
- "$TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME"
- rm install-jdk.sh
- rm jdk.tar.gz
- chmod +x gradlew
- "./gradlew assemble"

