sudo: required
language: java
install: skip
os: linux
dist: focal
env:
  global:
    -
jdk: 
- openjdk17
services:
- docker

before_install:

script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
- export JAVA_HOME=$HOME/openjdk17
- rm install-jdk.sh
- rm jdk.tar.gz
- cd Backend/
- chmod +x gradlew
- ./gradlew clean test --info
- ./gradlew build


